'use client'

import Link from 'next/link'
import { Activity, ArrowUpRight, CircleDollarSign, Code2, FolderKanban, GitPullRequest, ShieldCheck } from 'lucide-react'
import { bounties, stats } from '@/lib/mock-data'
import { BountyCard, DashboardShell, SectionHeader } from '@/components/dashboard-shell'

const activeWork = [{ title: 'Fix wallet connection issue', repo: 'quai-community/wallet-kit', pr: '#391', status: 'Verification in progress', reward: 400 }, { title: 'Improve SDK documentation', repo: 'open-source/sdk', pr: '#218', status: 'Waiting for maintainer review', reward: 150 }]

function Stat({ label, value, detail, icon: Icon }: { label: string; value: string; detail: string; icon: typeof Activity }) { return <div className="rounded-xl border border-border bg-card p-5"><div className="flex items-center justify-between text-muted-foreground"><span className="text-sm">{label}</span><Icon size={17} className="text-primary"/></div><div className="mt-4 metric-number text-foreground">{value}</div><div className="mt-1 text-xs text-muted-foreground">{detail}</div></div> }

export default function Dashboard() { return <DashboardShell><SectionHeader title="Good morning, Alex" description="Find funded work, contribute to open source, and get paid when your work is verified." action={<Link href="/dashboard/bounties" className="flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">Explore bounties <ArrowUpRight size={16}/></Link>} />
  <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Stat label="Available bounties" value={`${stats.available}`} detail="+4 this week" icon={FolderKanban}/><Stat label="Active bounties" value={`${stats.active}`} detail="In progress" icon={Activity}/><Stat label="Pending reviews" value={`${stats.reviews}`} detail="Awaiting verification" icon={ShieldCheck}/><Stat label="Completed" value={`${stats.completed}`} detail="All time" icon={Code2}/><Stat label="Total earned" value={`${stats.earned} QUAI`} detail="+420 this month" icon={CircleDollarSign}/></div>
  <div className="mt-8 grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><section><div className="mb-4 flex items-end justify-between"><div><h2 className="text-lg font-semibold">Recommended for you</h2><p className="mt-1 text-sm text-muted-foreground">Bounties matching your skills and interests.</p></div><Link href="/dashboard/bounties" className="text-sm font-semibold text-[#08784d]">View all</Link></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{bounties.slice(0, 3).map(bounty => <BountyCard bounty={bounty} key={bounty.id}/>)}</div></section><section className="rounded-xl border border-border bg-card p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Your active work</h2><p className="mt-1 text-xs text-muted-foreground">Keep an eye on what needs attention.</p></div><GitPullRequest size={18} className="text-primary"/></div><div className="mt-5 divide-y divide-border">{activeWork.map(work => <Link href="/dashboard/submissions" className="block py-4 first:pt-0 last:pb-0" key={work.pr}><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-semibold">{work.title}</h3><p className="mt-1 text-xs text-muted-foreground">{work.repo} · PR {work.pr}</p></div><span className="font-mono text-xs font-semibold text-[#08784d]">{work.reward} QUAI</span></div><div className="mt-3 flex items-center gap-2 text-xs text-muted-foreground"><span className="size-2 rounded-full bg-[#3B82F6]"/>{work.status}<span className="ml-auto text-foreground">View →</span></div></Link>)}</div></section></div>
  <section className="mt-8 rounded-xl border border-border bg-card p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Recent activity</h2><p className="mt-1 text-xs text-muted-foreground">Your latest verified work.</p></div><Link href="/dashboard/earnings" className="text-sm font-semibold text-[#08784d]">View earnings</Link></div><div className="mt-5 grid gap-4 md:grid-cols-3">{[['Bounty completed', 'Fix API timeout', '+250 QUAI', '2 hours ago'], ['PR submitted', 'Improve SDK documentation', '', '5 hours ago'], ['Review requested', 'Wallet connection issue', '', 'Yesterday']].map(([label, title, reward, time], index) => <div className="flex gap-3" key={label}><div className={`mt-1 grid size-7 shrink-0 place-items-center rounded-full ${index === 0 ? 'bg-green-wash text-[#08784d]' : 'bg-muted text-muted-foreground'}`}>{index === 0 ? <ShieldCheck size={15}/> : <GitPullRequest size={15}/>}</div><div><div className="text-xs text-muted-foreground">{label}</div><div className="mt-1 text-sm font-semibold">{title}</div><div className="mt-1 flex gap-2 text-xs text-muted-foreground"><span>{reward}</span><span>·</span><span>{time}</span></div></div></div>)}</div></section>
</DashboardShell> }
